services:
  mysql:
    image: mysql:8.0
    container_name: mysqlincident-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Prerna@9211
      MYSQL_DATABASE: cloudshield
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: